-- MySQL Script generated by MySQL Workbench
-- Qua 11 Abr 2018 16:36:38 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema echocardiogram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema echocardiogram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `echocardiogram` DEFAULT CHARACTER SET utf8 ;
USE `echocardiogram` ;

-- -----------------------------------------------------
-- Table `echocardiogram`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `echocardiogram`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(15) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(11) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `echocardiogram`.`health_insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `echocardiogram`.`health_insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `echocardiogram`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `echocardiogram`.`patient` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `birthday` DATE NOT NULL,
  `mother` VARCHAR(70) NULL,
  `address` TEXT NULL,
  `health_insurance_id` INT NULL,
  `health_insurance_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patient_health_insurance1_idx` (`health_insurance_id` ASC),
  CONSTRAINT `fk_patient_user1`
    FOREIGN KEY (`id`)
    REFERENCES `echocardiogram`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_health_insurance1`
    FOREIGN KEY (`health_insurance_id`)
    REFERENCES `echocardiogram`.`health_insurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `echocardiogram`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `echocardiogram`.`doctor` (
  `id` INT NOT NULL,
  `crm` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_doctor_user1`
    FOREIGN KEY (`id`)
    REFERENCES `echocardiogram`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `echocardiogram`.`echocardiogram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `echocardiogram`.`echocardiogram` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doctor_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `weight` DOUBLE NOT NULL,
  `height` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_echocardiogram_doctor1_idx` (`doctor_id` ASC),
  INDEX `fk_echocardiogram_patient1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_echocardiogram_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `echocardiogram`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_echocardiogram_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `echocardiogram`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
